version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./config/traefik.yml:/etc/traefik/traefik.yml
      - ./config/dynamic:/etc/traefik/dynamic
      # - ./config/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log/traefik
    env_file:
      - .env
